"""
PEVR Execution Lifecycle Logger

Captures the full Planner-Executor-Verifier-Replanner loop for debugging,
performance analysis, and error tracking.  Follows the same pattern as
``app.core.tot.tot_logger.ToTExecutionLogger``.

Usage::

    from app.core.perv.pevr_logger import PEVRLogger, get_pevr_logger

    pevr_log = get_pevr_logger(task="...", session_id="...")
    with pevr_log:
        pevr_log.log_planning(plan_steps=[...], duration_s=1.2)
        pevr_log.log_execution(tool_calls=[...], duration_s=3.4)
        pevr_log.log_verification(report={...}, duration_s=0.5)
        # ... loop continues ...
        pevr_log.log_finalization(answer="...", duration_s=0.8)
"""

import json
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from langchain_core.messages import BaseMessage

logger = logging.getLogger(__name__)


def _ts() -> str:
    """返回 ISO 格式的当前 UTC 时间戳（毫秒精度）。"""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def extract_token_usage(response: Any) -> Dict[str, int]:
    """从 LLM 响应中提取 token 用量。

    兼容 LangChain 新旧两种 token 统计格式:
    - usage_metadata (LangChain 0.2+): input_tokens / output_tokens / total_tokens
    - response_metadata.token_usage (旧版): prompt_tokens / completion_tokens / total_tokens

    Args:
        response: LangChain AIMessage 或类似对象。

    Returns:
        包含 prompt_tokens, completion_tokens, total_tokens 的字典。
    """
    # 优先使用 usage_metadata (LangChain 0.2+)
    usage = getattr(response, "usage_metadata", None)
    if usage and isinstance(usage, dict):
        return {
            "prompt_tokens": usage.get("input_tokens", 0) or 0,
            "completion_tokens": usage.get("output_tokens", 0) or 0,
            "total_tokens": usage.get("total_tokens", 0) or 0,
        }

    # 回退到 response_metadata.token_usage
    meta = getattr(response, "response_metadata", {})
    if isinstance(meta, dict):
        token_usage = meta.get("token_usage", {})
        if isinstance(token_usage, dict) and token_usage:
            return {
                "prompt_tokens": token_usage.get("prompt_tokens", 0) or 0,
                "completion_tokens": token_usage.get("completion_tokens", 0) or 0,
                "total_tokens": token_usage.get("total_tokens", 0) or 0,
            }

    return {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}

# Module-level logger name used by logging_config.py to create pevr.log
PEVR_LOGGER_NAME = "app.core.perv"


# ---------------------------------------------------------------------------
# Data records
# ---------------------------------------------------------------------------

@dataclass
class TokenUsage:
    """单次 LLM 调用的 token 用量记录。"""
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0

    def to_dict(self) -> Dict[str, int]:
        return {
            "prompt_tokens": self.prompt_tokens,
            "completion_tokens": self.completion_tokens,
            "total_tokens": self.total_tokens,
        }

    @classmethod
    def from_response(cls, response: Any) -> "TokenUsage":
        """从 LLM 响应中构建 TokenUsage。"""
        usage = extract_token_usage(response)
        return cls(
            prompt_tokens=usage["prompt_tokens"],
            completion_tokens=usage["completion_tokens"],
            total_tokens=usage["total_tokens"],
        )


@dataclass
class ToolCallRecord:
    """Record of a single tool call within PEVR execution."""
    step_id: str
    tool_name: str
    status: str = "success"          # "success" | "fail"
    duration_ms: float = 0.0
    error: Optional[str] = None
    output_preview: str = ""         # First 200 chars of output


@dataclass
class PlanStepRecord:
    """Record of a plan step generated by the planner."""
    step_id: str
    tool: str
    description: str = ""
    expected: str = ""


@dataclass
class SkillPolicyRecord:
    """Record of SkillPolicyNode execution within a PEVR loop."""
    policy_applied: bool = False
    plan_steps_in: int = 0              # 输入 plan 步骤数
    skill_refs_found: int = 0           # 提取到的 skill 引用数
    skill_refs: List[Dict[str, Any]] = field(default_factory=list)  # [{skill_name, skill_type, source_step}]
    matched_count: int = 0              # MATCH 阶段匹配数
    matched_skills: List[Dict[str, Any]] = field(default_factory=list)
    gate_results: List[Dict[str, Any]] = field(default_factory=list)
    guard_passed: bool = False
    guard_issues: List[str] = field(default_factory=list)
    compiled_count: int = 0             # 成功编译数
    compiled_skills: List[Dict[str, Any]] = field(default_factory=list)  # [{skill_name, compiled_tool}]
    plan_steps_out: int = 0             # 输出 plan 步骤数
    duration_ms: float = 0.0
    error: Optional[str] = None
    feature_enabled: bool = True


@dataclass
class LoopRecord:
    """Record of a single PEVR loop iteration (plan -> execute -> verify)."""
    loop_index: int
    start_time: float = 0.0
    start_ts: str = ""     # ISO 时间戳
    end_time: float = 0.0
    end_ts: str = ""       # ISO 时间戳

    # Planning phase
    plan_steps: List[PlanStepRecord] = field(default_factory=list)
    planning_duration_ms: float = 0.0
    planning_error: Optional[str] = None
    planning_tokens: TokenUsage = field(default_factory=TokenUsage)

    # SkillPolicy phase (between planning and execution)
    skill_policy: Optional[SkillPolicyRecord] = None

    # Execution phase
    tool_calls: List[ToolCallRecord] = field(default_factory=list)
    execution_duration_ms: float = 0.0
    execution_error: Optional[str] = None
    execution_tokens: TokenUsage = field(default_factory=TokenUsage)

    # Verification phase
    verification_passed: bool = False
    verification_coverage: float = 0.0
    verification_grounded: bool = False
    verification_reason: str = ""
    verification_missing: List[str] = field(default_factory=list)
    verification_duration_ms: float = 0.0
    verification_error: Optional[str] = None
    verification_tokens: TokenUsage = field(default_factory=TokenUsage)

    # Replanning phase (only when verification fails)
    replan_action: Optional[str] = None       # "append" | "replace" | "retry"
    replan_target_step: Optional[str] = None
    replan_new_steps_count: int = 0
    replan_duration_ms: float = 0.0
    replan_error: Optional[str] = None
    replan_tokens: TokenUsage = field(default_factory=TokenUsage)


# ---------------------------------------------------------------------------
# Main logger class
# ---------------------------------------------------------------------------

class PEVRLogger:
    """PEVR execution lifecycle logger.

    Tracks timing, errors, and structured data for each PEVR loop iteration.
    Designed as a context manager — ``__enter__`` logs the start,
    ``__exit__`` logs the end (or failure).

    Attributes:
        task: The user's original task text.
        session_id: Session identifier for correlation.
        loops: Completed loop records.
    """

    def __init__(self, task: str, session_id: str = ""):
        self.task = task
        self.session_id = session_id
        self.start_time: float = 0.0
        self.end_time: Optional[float] = None

        self.loops: List[LoopRecord] = []
        self._current_loop: Optional[LoopRecord] = None

        # Aggregated stats
        self.total_llm_calls: int = 0
        self.total_tool_calls: int = 0
        self.total_retries: int = 0
        self.total_prompt_tokens: int = 0
        self.total_completion_tokens: int = 0

        # Final result
        self.final_answer: Optional[str] = None
        self.final_error: Optional[str] = None
        self.finalization_tokens: TokenUsage = TokenUsage()

        # Config snapshot (set by orchestrator)
        self.config: Dict[str, Any] = {}

        # Custom events for learning integration tracking
        self._custom_events: List[Dict[str, Any]] = []

    # --- Context manager ---

    def __enter__(self) -> "PEVRLogger":
        self.start_time = time.time()
        logger.info(
            "[PEVR] === Session started === task=%s session=%s",
            self.task[:100],
            self.session_id,
        )
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.end_time = time.time()
        self._finalize_loop()
        duration_ms = (self.end_time - self.start_time) * 1000

        if exc_type:
            self.final_error = str(exc_val)
            logger.error(
                "[PEVR] === Session FAILED === error=%s duration=%.0fms "
                "loops=%d llm_calls=%d tool_calls=%d "
                "tokens[prompt=%d completion=%d]",
                exc_val,
                duration_ms,
                len(self.loops),
                self.total_llm_calls,
                self.total_tool_calls,
                self.total_prompt_tokens,
                self.total_completion_tokens,
                exc_info=(exc_type, exc_val, exc_tb),
            )
        else:
            logger.info(
                "[PEVR] === Session completed === duration=%.0fms "
                "loops=%d retries=%d llm_calls=%d tool_calls=%d "
                "tokens[prompt=%d completion=%d] "
                "answer_len=%d",
                duration_ms,
                len(self.loops),
                self.total_retries,
                self.total_llm_calls,
                self.total_tool_calls,
                self.total_prompt_tokens,
                self.total_completion_tokens,
                len(self.final_answer) if self.final_answer else 0,
            )

        # Auto-save trace
        self._auto_save_trace()

    # --- Loop lifecycle ---

    def _finalize_loop(self):
        """Finalize current loop and append to loops list."""
        if self._current_loop is not None:
            self._current_loop.end_time = time.time()
            self._current_loop.end_ts = _ts()
            self.loops.append(self._current_loop)
            self._current_loop = None

    def _ensure_loop(self, loop_index: int):
        """Ensure an active loop record, finalizing previous if index changed."""
        if (
            self._current_loop is None
            or self._current_loop.loop_index != loop_index
        ):
            self._finalize_loop()
            self._current_loop = LoopRecord(
                loop_index=loop_index,
                start_time=time.time(),
                start_ts=_ts(),
            )

    # --- Phase logging ---

    def log_planning(
        self,
        loop_index: int,
        plan_steps: List[Dict[str, Any]],
        duration_s: float,
        error: Optional[Exception] = None,
        token_usage: Optional[Dict[str, int]] = None,
    ):
        """Log the planning phase."""
        self._ensure_loop(loop_index)
        self.total_llm_calls += 1
        loop = self._current_loop

        loop.planning_duration_ms = duration_s * 1000
        if token_usage:
            loop.planning_tokens = TokenUsage(
                prompt_tokens=token_usage.get("prompt_tokens", 0),
                completion_tokens=token_usage.get("completion_tokens", 0),
                total_tokens=token_usage.get("total_tokens", 0),
            )
            self.total_prompt_tokens += loop.planning_tokens.prompt_tokens
            self.total_completion_tokens += loop.planning_tokens.completion_tokens

        loop.plan_steps = [
            PlanStepRecord(
                step_id=s.get("id", ""),
                tool=s.get("tool", ""),
                description=s.get("description", ""),
                expected=s.get("expected", ""),
            )
            for s in plan_steps
        ]

        if error:
            loop.planning_error = str(error)
            logger.error(
                "[PEVR] [%s] Planning FAILED at loop %d: %s (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                loop_index,
                error,
                loop.planning_duration_ms,
                loop.planning_tokens.prompt_tokens,
                loop.planning_tokens.completion_tokens,
            )
        else:
            logger.info(
                "[PEVR] [%s] Planning loop %d: %d steps generated (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                loop_index,
                len(plan_steps),
                loop.planning_duration_ms,
                loop.planning_tokens.prompt_tokens,
                loop.planning_tokens.completion_tokens,
            )
            # Log each step at DEBUG level
            for step in loop.plan_steps:
                logger.debug(
                    "[PEVR]   step %s: tool=%s desc=%s",
                    step.step_id,
                    step.tool,
                    step.description[:80],
                )

    def log_execution(
        self,
        loop_index: int,
        observations: List[Dict[str, Any]],
        duration_s: float,
        error: Optional[Exception] = None,
        token_usage: Optional[Dict[str, int]] = None,
    ):
        """Log the execution phase."""
        self._ensure_loop(loop_index)
        loop = self._current_loop

        loop.execution_duration_ms = duration_s * 1000
        if token_usage:
            loop.execution_tokens = TokenUsage(
                prompt_tokens=token_usage.get("prompt_tokens", 0),
                completion_tokens=token_usage.get("completion_tokens", 0),
                total_tokens=token_usage.get("total_tokens", 0),
            )
            self.total_prompt_tokens += loop.execution_tokens.prompt_tokens
            self.total_completion_tokens += loop.execution_tokens.completion_tokens

        for obs in observations:
            tc = ToolCallRecord(
                step_id=obs.get("step_id", ""),
                tool_name=obs.get("tool", "unknown"),
                status=obs.get("status", "unknown"),
                error=obs.get("error"),
                output_preview=str(obs.get("result", ""))[:200],
            )
            loop.tool_calls.append(tc)
            self.total_tool_calls += 1

        success_count = sum(1 for o in observations if o.get("status") == "success")
        self.total_llm_calls += 1  # executor uses at least 1 LLM call

        if error:
            loop.execution_error = str(error)
            logger.error(
                "[PEVR] [%s] Execution FAILED at loop %d: %s (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                loop_index,
                error,
                loop.execution_duration_ms,
                loop.execution_tokens.prompt_tokens,
                loop.execution_tokens.completion_tokens,
            )
        else:
            logger.info(
                "[PEVR] [%s] Execution loop %d: %d/%d tools succeeded (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                loop_index,
                success_count,
                len(observations),
                loop.execution_duration_ms,
                loop.execution_tokens.prompt_tokens,
                loop.execution_tokens.completion_tokens,
            )
            # Log each tool call at DEBUG
            for tc in loop.tool_calls:
                if tc.status == "success":
                    logger.debug(
                        "[PEVR]   %s: %s OK (%.0fms) preview=%s",
                        tc.step_id,
                        tc.tool_name,
                        tc.duration_ms,
                        tc.output_preview[:80],
                    )
                else:
                    logger.warning(
                        "[PEVR]   %s: %s FAILED error=%s",
                        tc.step_id,
                        tc.tool_name,
                        tc.error or "unknown",
                    )

    def log_verification(
        self,
        loop_index: int,
        report: Dict[str, Any],
        duration_s: float,
        error: Optional[Exception] = None,
        token_usage: Optional[Dict[str, int]] = None,
    ):
        """Log the verification phase."""
        self._ensure_loop(loop_index)
        self.total_llm_calls += 1
        loop = self._current_loop

        loop.verification_duration_ms = duration_s * 1000
        if token_usage:
            loop.verification_tokens = TokenUsage(
                prompt_tokens=token_usage.get("prompt_tokens", 0),
                completion_tokens=token_usage.get("completion_tokens", 0),
                total_tokens=token_usage.get("total_tokens", 0),
            )
            self.total_prompt_tokens += loop.verification_tokens.prompt_tokens
            self.total_completion_tokens += loop.verification_tokens.completion_tokens

        loop.verification_passed = report.get("passed", False)
        loop.verification_coverage = float(report.get("coverage", 0.0))
        loop.verification_grounded = bool(report.get("grounded", False))
        loop.verification_reason = str(report.get("reason", ""))
        loop.verification_missing = list(report.get("missing", []))

        if error:
            loop.verification_error = str(error)
            logger.error(
                "[PEVR] [%s] Verification FAILED (error) at loop %d: %s (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                loop_index,
                error,
                loop.verification_duration_ms,
                loop.verification_tokens.prompt_tokens,
                loop.verification_tokens.completion_tokens,
            )
        else:
            verdict = "PASSED" if loop.verification_passed else "FAILED"
            logger.info(
                "[PEVR] [%s] Verification loop %d: %s coverage=%.2f grounded=%s (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                loop_index,
                verdict,
                loop.verification_coverage,
                loop.verification_grounded,
                loop.verification_duration_ms,
                loop.verification_tokens.prompt_tokens,
                loop.verification_tokens.completion_tokens,
            )
            if not loop.verification_passed:
                logger.info(
                    "[PEVR]   reason: %s",
                    loop.verification_reason[:200],
                )
                if loop.verification_missing:
                    logger.info(
                        "[PEVR]   missing: %s",
                        loop.verification_missing,
                    )

    def log_replanning(
        self,
        loop_index: int,
        action: str,
        target_step: Optional[str],
        new_steps_count: int,
        duration_s: float,
        error: Optional[Exception] = None,
        token_usage: Optional[Dict[str, int]] = None,
    ):
        """Log the replanning phase."""
        self._ensure_loop(loop_index)
        self.total_llm_calls += 1
        self.total_retries += 1
        loop = self._current_loop

        loop.replan_action = action
        loop.replan_target_step = target_step
        loop.replan_new_steps_count = new_steps_count
        loop.replan_duration_ms = duration_s * 1000
        if token_usage:
            loop.replan_tokens = TokenUsage(
                prompt_tokens=token_usage.get("prompt_tokens", 0),
                completion_tokens=token_usage.get("completion_tokens", 0),
                total_tokens=token_usage.get("total_tokens", 0),
            )
            self.total_prompt_tokens += loop.replan_tokens.prompt_tokens
            self.total_completion_tokens += loop.replan_tokens.completion_tokens

        if error:
            loop.replan_error = str(error)
            logger.error(
                "[PEVR] [%s] Replanning FAILED at loop %d: %s (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                loop_index,
                error,
                loop.replan_duration_ms,
                loop.replan_tokens.prompt_tokens,
                loop.replan_tokens.completion_tokens,
            )
        else:
            logger.info(
                "[PEVR] [%s] Replanning loop %d: action=%s target=%s new_steps=%d (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                loop_index,
                action,
                target_step,
                new_steps_count,
                loop.replan_duration_ms,
                loop.replan_tokens.prompt_tokens,
                loop.replan_tokens.completion_tokens,
            )

    def log_finalization(
        self,
        answer: str,
        duration_s: float,
        error: Optional[Exception] = None,
        token_usage: Optional[Dict[str, int]] = None,
    ):
        """Log the finalization phase."""
        self._finalize_loop()
        self.total_llm_calls += 1
        self.final_answer = answer
        if token_usage:
            self.finalization_tokens = TokenUsage(
                prompt_tokens=token_usage.get("prompt_tokens", 0),
                completion_tokens=token_usage.get("completion_tokens", 0),
                total_tokens=token_usage.get("total_tokens", 0),
            )
            self.total_prompt_tokens += self.finalization_tokens.prompt_tokens
            self.total_completion_tokens += self.finalization_tokens.completion_tokens

        if error:
            logger.error(
                "[PEVR] [%s] Finalization FAILED: %s (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                error,
                duration_s * 1000,
                self.finalization_tokens.prompt_tokens,
                self.finalization_tokens.completion_tokens,
            )
        else:
            logger.info(
                "[PEVR] [%s] Finalization: %d chars (%.0fms) "
                "tokens[prompt=%d completion=%d]",
                _ts(),
                len(answer),
                duration_s * 1000,
                self.finalization_tokens.prompt_tokens,
                self.finalization_tokens.completion_tokens,
            )

    def log_skill_policy(
        self,
        loop_index: int,
        report: Dict[str, Any],
        duration_ms: float,
    ):
        """Log the SkillPolicy compilation phase.

        Records MATCH/GATE/COMPILE/GUARD results for each skill referenced
        in the plan.  Called by skill_policy_node after processing.

        Args:
            loop_index: Current loop index (same as retry_count).
            report: The SkillPolicyReport dict from skill_policy_node.
            duration_ms: Processing duration in milliseconds.
        """
        self._ensure_loop(loop_index)
        loop = self._current_loop

        rec = SkillPolicyRecord(
            policy_applied=report.get("policy_applied", False),
            plan_steps_in=report.get("plan_steps_in", 0),
            skill_refs_found=report.get("skill_refs_found", 0),
            skill_refs=report.get("skill_refs", []),
            matched_count=len(report.get("matched_skills", [])),
            matched_skills=[
                {"name": m.get("skill_name"), "type": m.get("skill_type"), "score": m.get("score")}
                for m in report.get("matched_skills", [])
            ],
            gate_results=report.get("gate_results", []),
            guard_passed=report.get("guard_passed", False),
            guard_issues=report.get("guard_issues", []),
            compiled_count=report.get("compiled_count", 0),
            compiled_skills=report.get("compiled_skills", []),
            plan_steps_out=report.get("plan_steps_out", 0),
            duration_ms=round(duration_ms, 1),
            error=report.get("error"),
            feature_enabled=report.get("feature_enabled", True),
        )
        loop.skill_policy = rec

        if rec.error:
            logger.error(
                "[PEVR] [%s] SkillPolicy FAILED at loop %d: %s (%.0fms)",
                _ts(), loop_index, rec.error, rec.duration_ms,
            )
        elif not rec.feature_enabled:
            logger.info(
                "[PEVR] [%s] SkillPolicy SKIP (disabled) at loop %d",
                _ts(), loop_index,
            )
        elif not rec.policy_applied:
            logger.info(
                "[PEVR] [%s] SkillPolicy PASS_THROUGH at loop %d: "
                "refs=%d matched=%d (%.0fms)",
                _ts(), loop_index, rec.skill_refs_found,
                rec.matched_count, rec.duration_ms,
            )
        else:
            allowed = [g for g in rec.gate_results if g.get("allowed")]
            rejected = [g for g in rec.gate_results if not g.get("allowed")]
            logger.info(
                "[PEVR] [%s] SkillPolicy COMPILED at loop %d: "
                "refs=%d matched=%d gate=%d/%d guard=%s "
                "plan=%d→%d (%.0fms)",
                _ts(), loop_index,
                rec.skill_refs_found, rec.matched_count,
                len(allowed), len(allowed) + len(rejected),
                rec.guard_passed,
                rec.plan_steps_in, rec.plan_steps_out,
                rec.duration_ms,
            )
            for cs in rec.compiled_skills:
                logger.debug(
                    "[PEVR]   compiled: %s → %s",
                    cs.get("skill_name"), cs.get("compiled_tool"),
                )
            for g in rejected:
                logger.debug(
                    "[PEVR]   rejected: %s reason=%s",
                    g.get("skill_name"), g.get("reason"),
                )

    def log_error(self, phase: str, error: Exception, context: Dict[str, Any] = None):
        """Log an unexpected error at any phase.

        Args:
            phase: Which phase the error occurred in.
            error: The exception.
            context: Optional additional context dict.
        """
        logger.error(
            "[PEVR] Unexpected error in %s: %s context=%s",
            phase,
            error,
            context or {},
            exc_info=True,
        )

    def log_node_error(
        self,
        node_name: str,
        error: Exception,
        state_summary: str = "",
    ):
        """Log a node execution error with state context.

        Args:
            node_name: Name of the graph node that failed.
            error: The exception.
            state_summary: Short summary of the state when the error occurred.
        """
        logger.error(
            "[PEVR] Node '%s' failed: %s state=%s",
            node_name,
            error,
            state_summary,
            exc_info=True,
        )

    def log_config(self, config: Dict[str, Any]):
        """Record the PEVR configuration snapshot."""
        self.config = config
        logger.info(
            "[PEVR] Config: max_retries=%d max_steps=%d max_llm_calls=%d strictness=%s",
            config.get("max_retries", "?"),
            config.get("max_steps", "?"),
            config.get("max_llm_calls", "?"),
            config.get("strictness", "?"),
        )

    def log_routing(
        self,
        decision: Dict[str, Any],
        duration_ms: float,
        error: Exception = None,
        token_usage: Dict[str, int] = None,
    ):
        """记录 PERV Router 路由决策。

        Args:
            decision: RouteDecision 字典。
            duration_ms: 路由耗时（毫秒）。
            error: 可选的异常信息。
            token_usage: 可选的 token 使用量。
        """
        logger.info(
            "[PEVR] Routing decision: mode=%s risk=%s reason=%s source=%s (%.0fms)",
            decision.get("mode"),
            decision.get("risk"),
            decision.get("reason"),
            decision.get("source"),
            duration_ms,
        )
        if error:
            logger.warning("[PEVR] Routing error: %s", error)
        if token_usage:
            logger.debug(
                "[PEVR] Routing token usage: prompt=%d completion=%d",
                token_usage.get("prompt_tokens", 0),
                token_usage.get("completion_tokens", 0),
            )

    def log_custom(self, event_type: str, data: Any = None, **kwargs):
        """Record a custom event for learning integration tracking.

        Used by orchestrator pre-hooks and post-hooks to track pattern
        retrieval, strategy injection, semantic history search, and
        learning results.

        Args:
            event_type: Event category (e.g. "pattern_retrieval",
                "strategy_injection", "semantic_history", "learning_result").
            data: Optional data payload (dict, int, str, etc.).
            **kwargs: Additional key-value pairs merged into the event.
        """
        event: Dict[str, Any] = {
            "type": event_type,
            "timestamp": time.time(),
            "ts": _ts(),
        }
        if data is not None:
            event["data"] = data
        event.update(kwargs)
        self._custom_events.append(event)
        logger.debug(
            "[PEVR] Custom event: type=%s data=%s",
            event_type,
            str(data)[:100] if data is not None else "None",
        )

    # --- Export ---

    def get_summary(self) -> Dict[str, Any]:
        """Get execution summary as dict (JSON-serializable)."""
        self._finalize_loop()
        total_duration_ms = (
            (self.end_time or time.time()) - self.start_time
        ) * 1000

        return {
            "mode": "pevr",
            "task": self.task[:200],
            "session_id": self.session_id,
            "config": self.config,
            "loops": [
                {
                    "loop_index": lp.loop_index,
                    "start_ts": lp.start_ts,
                    "end_ts": lp.end_ts,
                    "planning": {
                        "steps": len(lp.plan_steps),
                        "duration_ms": round(lp.planning_duration_ms, 1),
                        "error": lp.planning_error,
                        "tokens": lp.planning_tokens.to_dict(),
                    },
                    "skill_policy": {
                        "policy_applied": lp.skill_policy.policy_applied,
                        "feature_enabled": lp.skill_policy.feature_enabled,
                        "plan_steps_in": lp.skill_policy.plan_steps_in,
                        "skill_refs_found": lp.skill_policy.skill_refs_found,
                        "skill_refs": lp.skill_policy.skill_refs,
                        "matched_count": lp.skill_policy.matched_count,
                        "matched_skills": lp.skill_policy.matched_skills,
                        "gate_results": lp.skill_policy.gate_results,
                        "guard_passed": lp.skill_policy.guard_passed,
                        "guard_issues": lp.skill_policy.guard_issues,
                        "compiled_count": lp.skill_policy.compiled_count,
                        "compiled_skills": lp.skill_policy.compiled_skills,
                        "plan_steps_out": lp.skill_policy.plan_steps_out,
                        "duration_ms": lp.skill_policy.duration_ms,
                        "error": lp.skill_policy.error,
                    } if lp.skill_policy else None,
                    "execution": {
                        "tool_calls": [
                            {
                                "step_id": tc.step_id,
                                "tool_name": tc.tool_name,
                                "status": tc.status,
                                "duration_ms": round(tc.duration_ms, 1),
                                "error": tc.error,
                                "output_preview": tc.output_preview[:100],
                            }
                            for tc in lp.tool_calls
                        ],
                        "duration_ms": round(lp.execution_duration_ms, 1),
                        "error": lp.execution_error,
                        "tokens": lp.execution_tokens.to_dict(),
                    },
                    "verification": {
                        "passed": lp.verification_passed,
                        "coverage": lp.verification_coverage,
                        "grounded": lp.verification_grounded,
                        "reason": lp.verification_reason[:200],
                        "missing": lp.verification_missing,
                        "duration_ms": round(lp.verification_duration_ms, 1),
                        "error": lp.verification_error,
                        "tokens": lp.verification_tokens.to_dict(),
                    },
                    "replanning": {
                        "action": lp.replan_action,
                        "target_step": lp.replan_target_step,
                        "new_steps_count": lp.replan_new_steps_count,
                        "duration_ms": round(lp.replan_duration_ms, 1),
                        "error": lp.replan_error,
                        "tokens": lp.replan_tokens.to_dict(),
                    } if lp.replan_action else None,
                    "duration_ms": round(
                        (lp.end_time - lp.start_time) * 1000 if lp.end_time else 0,
                        1,
                    ),
                }
                for lp in self.loops
            ],
            "final_answer_length": len(self.final_answer) if self.final_answer else 0,
            "final_error": self.final_error,
            "finalization_tokens": self.finalization_tokens.to_dict(),
            "enrichment_events": [
                e for e in self._custom_events
                if e["type"] in ("pattern_retrieval", "strategy_injection", "semantic_history")
            ],
            "learning_events": [
                e for e in self._custom_events
                if e["type"] == "learning_result"
            ],
            "summary": {
                "total_loops": len(self.loops),
                "total_duration_ms": round(total_duration_ms, 1),
                "total_llm_calls": self.total_llm_calls,
                "total_tool_calls": self.total_tool_calls,
                "total_retries": self.total_retries,
                "total_prompt_tokens": self.total_prompt_tokens,
                "total_completion_tokens": self.total_completion_tokens,
            },
        }

    def save_trace(self, filepath: str):
        """Save full execution trace as JSON."""
        self._finalize_loop()
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(
                self.get_summary(),
                f,
                indent=2,
                ensure_ascii=False,
                default=str,
            )
        logger.info("[PEVR] Trace saved to %s", filepath)

    def _auto_save_trace(self):
        """Auto-save trace to logs/pevr_traces/ on session end."""
        try:
            settings = _get_settings()
            log_dir = getattr(settings, "log_dir", "logs")
            trace_dir = Path(log_dir) / "pevr_traces"
            trace_dir.mkdir(parents=True, exist_ok=True)

            import datetime
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            sid = self.session_id[:8] if self.session_id else "no-session"
            filename = trace_dir / f"pevr_{ts}_{sid}.json"
            self.save_trace(str(filename))
        except Exception as e:
            logger.debug("[PEVR] Auto-save trace failed: %s", e)


def _get_settings():
    """Lazy import settings to avoid circular dependency."""
    from app.config import get_settings
    return get_settings()


def get_pevr_logger(task: str, session_id: str = "") -> PEVRLogger:
    """Create a PEVRLogger instance.

    Convenience factory that matches the project's pattern for creating
    execution loggers (cf. ``ToTExecutionLogger``).
    """
    return PEVRLogger(task=task, session_id=session_id)
