# backend/app/core/settings_registry.py
"""
Settings Registry — Single source of truth for all user-configurable settings.

Each entry defines: key, type, default, range/options, group, section, descriptions, tooltips.
"""

from typing import Any, Dict, List, Literal, Optional
from dataclasses import dataclass, field


@dataclass
class SettingDefinition:
    key: str
    type: Literal["bool", "int", "float", "str", "select"]
    default: Any
    group: str
    section: str
    description_zh: str
    description_en: str
    tooltip_zh: str
    tooltip_en: str
    range_min: Optional[float] = None
    range_max: Optional[float] = None
    options: Optional[List[Dict[str, str]]] = None  # for select type: [{"value": "x", "label_zh": "...", "label_en": "..."}]

    def to_dict(self, current_value: Any = None) -> dict:
        d = {
            "key": self.key,
            "type": self.type,
            "default": self.default,
            "group": self.group,
            "section": self.section,
            "description_zh": self.description_zh,
            "description_en": self.description_en,
            "tooltip_zh": self.tooltip_zh,
            "tooltip_en": self.tooltip_en,
        }
        if current_value is not None:
            d["value"] = current_value
        else:
            d["value"] = self.default
        if self.range_min is not None:
            d["range"] = {"min": self.range_min, "max": self.range_max}
        if self.options:
            d["options"] = self.options
        return d


# Group definitions
SETTINGS_GROUPS = [
    {"id": "llm", "label_zh": "LLM 配置", "label_en": "LLM Configuration", "restart_required": False, "icon": "🤖"},
    {"id": "external_services", "label_zh": "外部服务", "label_en": "External Services", "restart_required": False, "icon": "🔌"},
    {"id": "skills", "label_zh": "技能管理", "label_en": "Skills Management", "restart_required": True, "icon": "📦"},
    {"id": "agent_behavior", "label_zh": "智能体行为", "label_en": "Agent Behavior", "restart_required": True, "icon": "💬"},
    {"id": "memory", "label_zh": "记忆系统", "label_en": "Memory System", "restart_required": True, "icon": "🧠"},
    {"id": "rag", "label_zh": "检索增强 & 知识库", "label_en": "RAG & Knowledge", "restart_required": True, "icon": "🔍"},
    {"id": "thinking", "label_zh": "思维模式", "label_en": "Thinking Modes", "restart_required": True, "icon": "🌳"},
    {"id": "performance", "label_zh": "性能优化", "label_en": "Performance", "restart_required": True, "icon": "⚡"},
    {"id": "logging", "label_zh": "日志 & 调试", "label_en": "Logging & Debug", "restart_required": True, "icon": "📝"},
    {"id": "interface", "label_zh": "界面设置", "label_en": "Interface", "restart_required": False, "icon": "🌐"},
    {"id": "tools_security", "label_zh": "工具 & 安全", "label_en": "Tools & Security", "restart_required": True, "icon": "🛡️"},
    {"id": "experimental", "label_zh": "实验性功能", "label_en": "Experimental", "restart_required": True, "icon": "🧪"},
]


# All settings definitions
SETTINGS_DEFINITIONS: List[SettingDefinition] = [
    # ===== Group: LLM =====
    SettingDefinition(
        key="llm_request_timeout",
        type="int",
        default=120,
        group="llm",
        section="general",
        description_zh="请求超时时间",
        description_en="Request timeout",
        tooltip_zh="LLM API 请求的超时时间（秒）。如果 API 响应慢，可以适当增大。建议范围：30-300。",
        tooltip_en="Timeout in seconds for LLM API requests. Increase if API is slow. Recommended: 30-300.",
        range_min=10,
        range_max=600,
    ),
    SettingDefinition(
        key="max_prompt_length",
        type="int",
        default=20000,
        group="llm",
        section="general",
        description_zh="最大 Prompt 长度",
        description_en="Max Prompt Length",
        tooltip_zh="系统 Prompt 的最大字符数。超出时触发截断。较大的值提供更多上下文但消耗更多 token。",
        tooltip_en="Maximum characters for system prompt. Truncation triggers when exceeded. Larger values provide more context but cost more tokens.",
        range_min=5000,
        range_max=50000,
    ),

    # ===== Group: Agent Behavior — Agent Execution =====
    SettingDefinition(
        key="enable_smart_stopping",
        type="bool",
        default=True,
        group="agent_behavior",
        section="agent_execution",
        description_zh="智能停止",
        description_en="Smart Stopping",
        tooltip_zh="检测冗余循环，自动终止无效工具调用。关闭后 Agent 会一直调用工具直到达到最大轮次。",
        tooltip_en="Detect redundant loops and auto-terminate ineffective tool calls. Disabling means Agent runs until max rounds.",
    ),
    SettingDefinition(
        key="max_tool_rounds",
        type="int",
        default=50,
        group="agent_behavior",
        section="agent_execution",
        description_zh="最大工具轮次",
        description_en="Max Tool Rounds",
        tooltip_zh="当 Agent 在单次对话中调用工具的次数达到此上限时，将强制停止工具调用并生成最终回答。设置过低可能导致任务未完成，过高可能陷入无效循环。建议范围：20-100。",
        tooltip_en="When the Agent reaches this limit of tool calls in a single turn, it will stop and generate a final answer. Too low may leave tasks incomplete; too high may cause infinite loops. Recommended: 20-100.",
        range_min=1,
        range_max=200,
    ),
    SettingDefinition(
        key="redundancy_detection_window",
        type="int",
        default=3,
        group="agent_behavior",
        section="agent_execution",
        description_zh="冗余检测窗口",
        description_en="Redundancy Window",
        tooltip_zh="检测重复工具调用的滑动窗口大小。窗口内出现相同工具调用达到阈值时触发智能停止。",
        tooltip_en="Sliding window size for detecting repeated tool calls. Triggers smart stop when identical calls appear within window.",
        range_min=1,
        range_max=10,
    ),
    SettingDefinition(
        key="sufficiency_evaluation_interval",
        type="int",
        default=5,
        group="agent_behavior",
        section="agent_execution",
        description_zh="充分性评估间隔",
        description_en="Sufficiency Interval",
        tooltip_zh="每隔几轮工具调用评估一次是否已充分回答。较小的值更频繁评估但消耗更多 token。",
        tooltip_en="Evaluate every N tool calls whether the answer is sufficient. Smaller values are more frequent but cost more tokens.",
        range_min=1,
        range_max=20,
    ),

    # ===== Group: Agent Behavior — Reflection =====
    SettingDefinition(
        key="enable_agent_reflection",
        type="bool",
        default=True,
        group="agent_behavior",
        section="reflection",
        description_zh="启用反思",
        description_en="Enable Reflection",
        tooltip_zh="Agent 完成任务后自我评估回答质量。开启后会多一次 LLM 调用用于质量评估。",
        tooltip_en="Agent self-evaluates answer quality after task completion. Adds one extra LLM call for evaluation.",
    ),
    SettingDefinition(
        key="agent_reflection_quality_threshold",
        type="float",
        default=6.0,
        group="agent_behavior",
        section="reflection",
        description_zh="质量阈值",
        description_en="Quality Threshold",
        tooltip_zh="低于此分数（0-10）时触发反思重做。较高的值意味着更严格的质量要求。",
        tooltip_en="Score threshold (0-10) below which reflection redo is triggered. Higher values mean stricter quality requirements.",
        range_min=0,
        range_max=10,
    ),
    SettingDefinition(
        key="enable_reflection_learning",
        type="bool",
        default=True,
        group="agent_behavior",
        section="reflection",
        description_zh="反思学习",
        description_en="Reflection Learning",
        tooltip_zh="从反思结果中学习并改进后续行为。关闭后反思仅评估不积累经验。",
        tooltip_en="Learn from reflection results to improve future behavior. Disabling means reflection evaluates but doesn't accumulate experience.",
    ),
    SettingDefinition(
        key="evaluation_cache_enabled",
        type="bool",
        default=True,
        group="agent_behavior",
        section="reflection",
        description_zh="评估缓存",
        description_en="Evaluation Cache",
        tooltip_zh="缓存相似任务的评估结果避免重复调用 LLM。开启可减少 token 消耗。",
        tooltip_en="Cache evaluation results for similar tasks to avoid redundant LLM calls. Reduces token consumption.",
    ),

    # ===== Group: Agent Behavior — Meta Policy & TCA =====
    SettingDefinition(
        key="enable_meta_policy",
        type="bool",
        default=True,
        group="agent_behavior",
        section="meta_policy",
        description_zh="元策略",
        description_en="Meta Policy",
        tooltip_zh="根据任务特征动态选择最佳执行策略。关闭后使用固定策略。",
        tooltip_en="Dynamically select best execution strategy based on task characteristics. Disabling uses fixed strategy.",
    ),
    SettingDefinition(
        key="enable_tca",
        type="bool",
        default=True,
        group="agent_behavior",
        section="meta_policy",
        description_zh="任务分解 (TCA)",
        description_en="Task Decomposition (TCA)",
        tooltip_zh="使用神经网络判断任务复杂度并决定是否分解为子任务。关闭后所有任务统一处理。",
        tooltip_en="Use neural network to assess task complexity and decide whether to decompose into subtasks. Disabling treats all tasks uniformly.",
    ),

    # ===== Group: Agent Behavior — Watchdog =====
    SettingDefinition(
        key="enable_watchdog",
        type="bool",
        default=True,
        group="agent_behavior",
        section="watchdog",
        description_zh="看门狗",
        description_en="Watchdog",
        tooltip_zh="监控 Agent 运行状态，检测卡死和重复循环。关闭后无法自动恢复异常状态。",
        tooltip_en="Monitor Agent runtime status, detect stuck and repetitive loops. Disabling means no automatic recovery from abnormal states.",
    ),
    SettingDefinition(
        key="watchdog_heartbeat_timeout",
        type="int",
        default=60,
        group="agent_behavior",
        section="watchdog",
        description_zh="心跳超时",
        description_en="Heartbeat Timeout",
        tooltip_zh="看门狗心跳超时时间（秒）。超过此时间无心跳则判定为卡死。",
        tooltip_en="Watchdog heartbeat timeout in seconds. No heartbeat within this time means Agent is stuck.",
        range_min=10,
        range_max=300,
    ),
    SettingDefinition(
        key="watchdog_poll_interval",
        type="int",
        default=5,
        group="agent_behavior",
        section="watchdog",
        description_zh="轮询间隔",
        description_en="Poll Interval",
        tooltip_zh="看门狗检查间隔（秒）。较小的值检测更快但消耗更多资源。",
        tooltip_en="Watchdog check interval in seconds. Smaller values detect faster but use more resources.",
        range_min=1,
        range_max=30,
    ),
    SettingDefinition(
        key="watchdog_stuck_threshold",
        type="int",
        default=4,
        group="agent_behavior",
        section="watchdog",
        description_zh="卡死阈值",
        description_en="Stuck Threshold",
        tooltip_zh="连续多少次心跳超时后判定为卡死并触发恢复。",
        tooltip_en="Number of consecutive heartbeat timeouts before triggering recovery.",
        range_min=1,
        range_max=10,
    ),
    SettingDefinition(
        key="watchdog_repeat_threshold",
        type="int",
        default=10,
        group="agent_behavior",
        section="watchdog",
        description_zh="重复阈值",
        description_en="Repeat Threshold",
        tooltip_zh="相同输出连续出现的次数阈值，超过后判定为循环卡死。",
        tooltip_en="Threshold for consecutive identical outputs before being determined as a repetitive loop.",
        range_min=1,
        range_max=30,
    ),
    SettingDefinition(
        key="watchdog_max_runtime",
        type="int",
        default=1800,
        group="agent_behavior",
        section="watchdog",
        description_zh="最大运行时间",
        description_en="Max Runtime",
        tooltip_zh="单次 Agent 运行的最大时间（秒）。超过后强制终止。",
        tooltip_en="Maximum runtime in seconds for a single Agent execution. Force-terminates when exceeded.",
        range_min=60,
        range_max=7200,
    ),

    # ===== Group: Agent Behavior — Session Management =====
    SettingDefinition(
        key="session_timeout",
        type="int",
        default=3600,
        group="agent_behavior",
        section="session_management",
        description_zh="会话超时",
        description_en="Session Timeout",
        tooltip_zh="会话空闲超时时间（秒）。超过此时间无活动则关闭会话。",
        tooltip_en="Session idle timeout in seconds. Session closes after this period of inactivity.",
        range_min=300,
        range_max=86400,
    ),
    SettingDefinition(
        key="max_message_history",
        type="int",
        default=100,
        group="agent_behavior",
        section="session_management",
        description_zh="最大消息数",
        description_en="Max Message History",
        tooltip_zh="保留在上下文窗口中的最大消息数量。较大的值保留更多历史但消耗更多 token。",
        tooltip_en="Maximum messages kept in context window. Larger values retain more history but cost more tokens.",
        range_min=10,
        range_max=500,
    ),
    SettingDefinition(
        key="session_retention_days",
        type="int",
        default=30,
        group="agent_behavior",
        section="session_management",
        description_zh="保留天数",
        description_en="Retention Days",
        tooltip_zh="会话文件保留天数。超过后自动清理。",
        tooltip_en="Days to retain session files. Auto-cleaned after this period.",
        range_min=1,
        range_max=365,
    ),
    SettingDefinition(
        key="session_archive_on_delete",
        type="bool",
        default=True,
        group="agent_behavior",
        section="session_management",
        description_zh="删除前归档",
        description_en="Archive on Delete",
        tooltip_zh="删除会话前先归档到事件日志，防止数据丢失。",
        tooltip_en="Archive session to event log before deletion to prevent data loss.",
    ),

    # ===== Group: Memory — Master Switches =====
    SettingDefinition(
        key="enable_memory_extraction",
        type="bool",
        default=True,
        group="memory",
        section="master_switches",
        description_zh="记忆提取",
        description_en="Memory Extraction",
        tooltip_zh="从对话中自动提取重要信息存入记忆。关闭后 Agent 不会记住对话中的关键信息。",
        tooltip_en="Automatically extract important information from conversations into memory. Disabling means Agent won't remember key info.",
    ),
    SettingDefinition(
        key="enable_semantic_search",
        type="bool",
        default=True,
        group="memory",
        section="master_switches",
        description_zh="语义搜索",
        description_en="Semantic Search",
        tooltip_zh="使用向量相似度搜索历史记忆。关闭后仅用关键词匹配。",
        tooltip_en="Use vector similarity to search historical memories. Disabling falls back to keyword matching only.",
    ),
    SettingDefinition(
        key="enable_user_profile_learning",
        type="bool",
        default=True,
        group="memory",
        section="master_switches",
        description_zh="用户画像学习",
        description_en="User Profile Learning",
        tooltip_zh="自动学习用户偏好、专业背景等信息，用于个性化回答。",
        tooltip_en="Automatically learn user preferences and background for personalized responses.",
    ),
    SettingDefinition(
        key="enable_long_term_memory",
        type="bool",
        default=True,
        group="memory",
        section="master_switches",
        description_zh="长期记忆",
        description_en="Long-term Memory",
        tooltip_zh="将重要记忆长期保存，跨会话可用。关闭后记忆仅在当前会话有效。",
        tooltip_en="Persist important memories across sessions. Disabling means memories only last within current session.",
    ),
    SettingDefinition(
        key="enable_memory_engine",
        type="bool",
        default=False,
        group="memory",
        section="master_switches",
        description_zh="记忆引擎",
        description_en="Memory Engine",
        tooltip_zh="启用第二代记忆引擎（实验性）。提供更智能的记忆管理和检索。",
        tooltip_en="Enable 2nd-gen memory engine (experimental). Provides smarter memory management and retrieval.",
    ),
    SettingDefinition(
        key="enable_entity_profile",
        type="bool",
        default=False,
        group="memory",
        section="master_switches",
        description_zh="实体关系画像",
        description_en="Entity & Relation Profiling",
        tooltip_zh="自动识别对话中的实体（人名、地点、概念等），构建关系图谱，帮助 Agent 理解上下文关联（实验性）。",
        tooltip_en="Automatically identify entities (people, places, concepts) in conversations and build relationship graphs to help Agent understand contextual connections (experimental).",
    ),

    # ===== Group: Memory — Extraction =====
    SettingDefinition(
        key="memory_extraction_interval",
        type="int",
        default=5,
        group="memory",
        section="extraction",
        description_zh="提取间隔",
        description_en="Extraction Interval",
        tooltip_zh="每隔几轮对话执行一次记忆提取。较小的值更频繁但消耗更多 token。",
        tooltip_en="Run memory extraction every N conversation turns. Smaller values are more frequent but cost more tokens.",
        range_min=1,
        range_max=20,
    ),
    SettingDefinition(
        key="memory_min_confidence",
        type="float",
        default=0.6,
        group="memory",
        section="extraction",
        description_zh="最低置信度",
        description_en="Min Confidence",
        tooltip_zh="记忆提取的最低置信度阈值（0-1）。只有置信度高于此值的信息才会被保存。",
        tooltip_en="Minimum confidence threshold (0-1) for memory extraction. Only info above this threshold is saved.",
        range_min=0,
        range_max=1,
    ),
    SettingDefinition(
        key="memory_max_conversations",
        type="int",
        default=100,
        group="memory",
        section="extraction",
        description_zh="最大对话数",
        description_en="Max Conversations",
        tooltip_zh="用于记忆索引的最大对话数量。较大的值覆盖更多历史但增加搜索开销。",
        tooltip_en="Maximum number of conversations to index for memory. Larger values cover more history but increase search cost.",
        range_min=10,
        range_max=1000,
    ),
    SettingDefinition(
        key="user_profile_update_interval",
        type="int",
        default=10,
        group="memory",
        section="extraction",
        description_zh="画像更新间隔",
        description_en="Profile Update Interval",
        tooltip_zh="每隔几次记忆提取更新一次用户画像。较大的值减少开销但更新更慢。",
        tooltip_en="Update user profile every N memory extractions. Larger values reduce overhead but update slower.",
        range_min=1,
        range_max=50,
    ),
    SettingDefinition(
        key="memory_extraction_max_retries",
        type="int",
        default=2,
        group="memory",
        section="extraction",
        description_zh="提取最大重试",
        description_en="Extraction Max Retries",
        tooltip_zh="记忆提取 JSON 解析失败时的最大重试次数。",
        tooltip_en="Maximum retries when memory extraction JSON parsing fails.",
        range_min=0,
        range_max=5,
    ),

    # ===== Group: Memory — Long-term =====
    SettingDefinition(
        key="long_term_memory_max_items",
        type="int",
        default=50,
        group="memory",
        section="long_term",
        description_zh="最大条目数",
        description_en="Max Items",
        tooltip_zh="长期记忆保存的最大条目数。超出后自动修剪低优先级的记忆。",
        tooltip_en="Maximum items in long-term memory. Excess items are auto-pruned by priority.",
        range_min=10,
        range_max=500,
    ),
    SettingDefinition(
        key="long_term_memory_prune_threshold",
        type="float",
        default=0.3,
        group="memory",
        section="long_term",
        description_zh="修剪阈值",
        description_en="Prune Threshold",
        tooltip_zh="长期记忆修剪的优先级阈值（0-1）。低于此值的记忆在修剪时被移除。",
        tooltip_en="Priority threshold (0-1) for long-term memory pruning. Items below this value are removed during pruning.",
        range_min=0,
        range_max=1,
    ),

    # ===== Group: Memory — Knowledge Graph =====
    SettingDefinition(
        key="enable_kg",
        type="bool",
        default=True,
        group="memory",
        section="knowledge_graph",
        description_zh="知识图谱",
        description_en="Knowledge Graph",
        tooltip_zh="从对话中提取实体关系构建知识图谱。增强 Agent 的关联推理能力。",
        tooltip_en="Extract entity relationships from conversations to build a knowledge graph. Enhances associative reasoning.",
    ),
    SettingDefinition(
        key="kg_store_backend",
        type="select",
        default="sqlite",
        group="memory",
        section="knowledge_graph",
        description_zh="存储后端",
        description_en="Store Backend",
        tooltip_zh="知识图谱的存储后端。SQLite 为内置轻量方案，Neo4j 适合大规模图谱。",
        tooltip_en="Knowledge graph storage backend. SQLite is built-in and lightweight; Neo4j for large-scale graphs.",
        options=[
            {"value": "sqlite", "label_zh": "SQLite（内置）", "label_en": "SQLite (built-in)"},
            {"value": "neo4j", "label_zh": "Neo4j", "label_en": "Neo4j"},
        ],
    ),
    SettingDefinition(
        key="kg_max_triples_per_turn",
        type="int",
        default=10,
        group="memory",
        section="knowledge_graph",
        description_zh="每轮最大三元组",
        description_en="Max Triples Per Turn",
        tooltip_zh="每轮对话提取的最大知识三元组数量。",
        tooltip_en="Maximum knowledge triples to extract per conversation turn.",
        range_min=1,
        range_max=50,
    ),
    SettingDefinition(
        key="kg_confidence_threshold",
        type="float",
        default=0.5,
        group="memory",
        section="knowledge_graph",
        description_zh="置信度阈值",
        description_en="Confidence Threshold",
        tooltip_zh="知识三元组提取的最低置信度（0-1）。",
        tooltip_en="Minimum confidence (0-1) for knowledge triple extraction.",
        range_min=0,
        range_max=1,
    ),
    SettingDefinition(
        key="similarity_threshold",
        type="float",
        default=0.7,
        group="memory",
        section="knowledge_graph",
        description_zh="相似度阈值",
        description_en="Similarity Threshold",
        tooltip_zh="语义搜索的最低相似度阈值（0-1）。较高的值要求更精确的匹配。",
        tooltip_en="Minimum similarity for semantic search (0-1). Higher values require more precise matches.",
        range_min=0,
        range_max=1,
    ),
    SettingDefinition(
        key="similarity_block_threshold",
        type="float",
        default=0.95,
        group="memory",
        section="knowledge_graph",
        description_zh="去重阈值",
        description_en="Block Threshold",
        tooltip_zh="近重复检测阈值（0-1）。超过此相似度的记忆被视为重复并跳过。",
        tooltip_en="Near-duplicate detection threshold (0-1). Memories above this similarity are treated as duplicates.",
        range_min=0,
        range_max=1,
    ),

    # ===== Group: Memory — Wiki =====
    SettingDefinition(
        key="enable_wiki",
        type="bool",
        default=True,
        group="memory",
        section="wiki",
        description_zh="LLM Wiki",
        description_en="LLM Wiki",
        tooltip_zh="让 Agent 自主构建知识库页面，记录学到的知识以备后续使用。",
        tooltip_en="Let Agent autonomously build knowledge base pages, recording learned knowledge for future use.",
    ),
    SettingDefinition(
        key="wiki_max_page_size",
        type="int",
        default=5000,
        group="memory",
        section="wiki",
        description_zh="最大页面大小",
        description_en="Max Page Size",
        tooltip_zh="单个 Wiki 页面的最大字符数。",
        tooltip_en="Maximum character count per Wiki page.",
        range_min=1000,
        range_max=20000,
    ),
    SettingDefinition(
        key="wiki_write_threshold",
        type="float",
        default=0.7,
        group="memory",
        section="wiki",
        description_zh="写入阈值",
        description_en="Write Threshold",
        tooltip_zh="Agent 判断知识值得写入 Wiki 的最低置信度（0-1）。",
        tooltip_en="Minimum confidence (0-1) for Agent to decide knowledge is worth writing to Wiki.",
        range_min=0,
        range_max=1,
    ),
    SettingDefinition(
        key="wiki_evidence_required",
        type="bool",
        default=True,
        group="memory",
        section="wiki",
        description_zh="需要证据",
        description_en="Evidence Required",
        tooltip_zh="写入 Wiki 前必须提供信息来源证据。关闭后 Agent 可自由写入。",
        tooltip_en="Require source evidence before writing to Wiki. Disabling allows Agent to write freely.",
    ),

    # ===== Group: Memory — Decay =====
    SettingDefinition(
        key="memory_ttl_default_days",
        type="int",
        default=90,
        group="memory",
        section="decay",
        description_zh="默认存活天数",
        description_en="Default TTL Days",
        tooltip_zh="新记忆的默认存活天数。超过后自动衰减。",
        tooltip_en="Default time-to-live in days for new memories. Auto-decays after this period.",
        range_min=7,
        range_max=365,
    ),
    SettingDefinition(
        key="memory_decay_cron_hours",
        type="int",
        default=24,
        group="memory",
        section="decay",
        description_zh="衰减检查间隔",
        description_en="Decay Check Interval",
        tooltip_zh="每隔多少小时执行一次记忆衰减检查。",
        tooltip_en="Hours between memory decay checks.",
        range_min=1,
        range_max=168,
    ),
    SettingDefinition(
        key="memory_decay_factor",
        type="float",
        default=0.01,
        group="memory",
        section="decay",
        description_zh="衰减因子",
        description_en="Decay Factor",
        tooltip_zh="每次衰减检查时记忆优先级的降低幅度（0-1）。较小的值衰减更慢。",
        tooltip_en="Priority reduction per decay check (0-1). Smaller values decay slower.",
        range_min=0,
        range_max=1,
    ),

    # ===== Group: Memory — Markdown =====
    SettingDefinition(
        key="md_auto_sync",
        type="bool",
        default=True,
        group="memory",
        section="markdown",
        description_zh="自动同步",
        description_en="Auto Sync",
        tooltip_zh="自动将记忆同步为 Markdown 文件。关闭后需手动触发同步。",
        tooltip_en="Automatically sync memories to Markdown files. Disabling requires manual sync.",
    ),
    SettingDefinition(
        key="md_min_confidence",
        type="float",
        default=0.7,
        group="memory",
        section="markdown",
        description_zh="最低置信度",
        description_en="Min Confidence",
        tooltip_zh="写入 Markdown 文件的最低记忆置信度（0-1）。",
        tooltip_en="Minimum memory confidence (0-1) to write to Markdown files.",
        range_min=0,
        range_max=1,
    ),

    # ===== Group: RAG =====
    SettingDefinition(
        key="enable_rag",
        type="bool",
        default=True,
        group="rag",
        section="general",
        description_zh="检索增强",
        description_en="RAG",
        tooltip_zh="启用检索增强生成，从知识库检索相关内容辅助回答。关闭后 Agent 不使用知识库。",
        tooltip_en="Enable Retrieval-Augmented Generation. Disabling means Agent won't use knowledge base.",
    ),
    SettingDefinition(
        key="embedding_model",
        type="str",
        default="text-embedding-ada-002",
        group="rag",
        section="general",
        description_zh="Embedding 模型",
        description_en="Embedding Model",
        tooltip_zh="用于文本向量化的模型名称。需与 API 提供商支持的模型一致。",
        tooltip_en="Model name for text vectorization. Must match a model supported by your API provider.",
    ),
    SettingDefinition(
        key="vector_store_type",
        type="select",
        default="chroma",
        group="rag",
        section="general",
        description_zh="向量存储",
        description_en="Vector Store",
        tooltip_zh="向量数据库类型。ChromaDB 为内置方案，Simple 为轻量文件存储。",
        tooltip_en="Vector database type. ChromaDB is built-in; Simple is lightweight file-based storage.",
        options=[
            {"value": "chroma", "label_zh": "ChromaDB", "label_en": "ChromaDB"},
            {"value": "simple", "label_zh": "Simple（文件）", "label_en": "Simple (file)"},
        ],
    ),
    SettingDefinition(
        key="hybrid_search_alpha",
        type="float",
        default=0.5,
        group="rag",
        section="general",
        description_zh="混合搜索权重",
        description_en="Hybrid Search Alpha",
        tooltip_zh="混合搜索中向量搜索与关键词搜索的权重（0=纯关键词，1=纯向量）。",
        tooltip_en="Weight between vector and keyword search in hybrid mode (0=pure keyword, 1=pure vector).",
        range_min=0,
        range_max=1,
    ),
    SettingDefinition(
        key="retrieval_top_k",
        type="int",
        default=5,
        group="rag",
        section="general",
        description_zh="检索数量",
        description_en="Retrieval Top-K",
        tooltip_zh="每次检索返回的最大文档片段数。较大的值提供更多上下文但增加噪声。",
        tooltip_en="Maximum document chunks returned per retrieval. More context but more noise with larger values.",
        range_min=1,
        range_max=20,
    ),
    SettingDefinition(
        key="chunk_size",
        type="int",
        default=512,
        group="rag",
        section="general",
        description_zh="分块大小",
        description_en="Chunk Size",
        tooltip_zh="文档分块的字符数。较小的块更精确但可能丢失上下文。",
        tooltip_en="Document chunk size in characters. Smaller chunks are more precise but may lose context.",
        range_min=128,
        range_max=2048,
    ),
    SettingDefinition(
        key="chunk_overlap",
        type="int",
        default=50,
        group="rag",
        section="general",
        description_zh="分块重叠",
        description_en="Chunk Overlap",
        tooltip_zh="相邻分块之间的重叠字符数。增加重叠可以保留跨块边界的信息。",
        tooltip_en="Overlap characters between adjacent chunks. Preserves information across chunk boundaries.",
        range_min=0,
        range_max=512,
    ),
    SettingDefinition(
        key="embedding_fallback",
        type="select",
        default="sentence-transformers",
        group="rag",
        section="general",
        description_zh="Embedding 回退",
        description_en="Embedding Fallback",
        tooltip_zh="当主 Embedding 模型不可时的回退方案。",
        tooltip_en="Fallback when primary embedding model is unavailable.",
        options=[
            {"value": "ollama", "label_zh": "Ollama", "label_en": "Ollama"},
            {"value": "sentence-transformers", "label_zh": "Sentence-Transformers", "label_en": "Sentence-Transformers"},
            {"value": "disable", "label_zh": "禁用", "label_en": "Disable"},
        ],
    ),
    SettingDefinition(
        key="max_batch_files",
        type="int",
        default=20,
        group="rag",
        section="general",
        description_zh="批量上传上限",
        description_en="Max Batch Files",
        tooltip_zh="单次批量上传的最大文件数量。",
        tooltip_en="Maximum files per batch upload.",
        range_min=1,
        range_max=100,
    ),

    # ===== Group: RAG — Caching =====
    SettingDefinition(
        key="enable_semantic_search_cache",
        type="bool",
        default=True,
        group="rag",
        section="caching",
        description_zh="语义搜索缓存",
        description_en="Semantic Search Cache",
        tooltip_zh="缓存语义搜索结果，减少重复检索。开启可降低延迟和 token 消耗。",
        tooltip_en="Cache semantic search results to reduce repeated retrieval. Reduces latency and token cost.",
    ),
    SettingDefinition(
        key="semantic_search_cache_ttl",
        type="int",
        default=300,
        group="rag",
        section="caching",
        description_zh="缓存过期时间",
        description_en="Cache TTL",
        tooltip_zh="语义搜索缓存的有效时间（秒）。",
        tooltip_en="Semantic search cache TTL in seconds.",
        range_min=30,
        range_max=3600,
    ),
    SettingDefinition(
        key="enable_context_cache",
        type="bool",
        default=True,
        group="rag",
        section="caching",
        description_zh="上下文缓存",
        description_en="Context Cache",
        tooltip_zh="缓存对话上下文以加速 Prompt 组装。",
        tooltip_en="Cache conversation context to speed up prompt assembly.",
    ),
    SettingDefinition(
        key="context_cache_size",
        type="int",
        default=64,
        group="rag",
        section="caching",
        description_zh="上下文缓存大小",
        description_en="Context Cache Size",
        tooltip_zh="缓存的上下文条目数量。",
        tooltip_en="Number of cached context entries.",
        range_min=10,
        range_max=256,
    ),
    SettingDefinition(
        key="enable_prompt_cache",
        type="bool",
        default=True,
        group="rag",
        section="caching",
        description_zh="Prompt 缓存",
        description_en="Prompt Cache",
        tooltip_zh="缓存已组装的 Prompt，避免重复构建。开启可减少重复计算。",
        tooltip_en="Cache assembled prompts to avoid repeated construction. Reduces redundant computation.",
    ),

    # ===== Group: Thinking — ToT =====
    SettingDefinition(
        key="enable_tot",
        type="bool",
        default=True,
        group="thinking",
        section="tot",
        description_zh="思维树 (ToT)",
        description_en="Tree of Thoughts",
        tooltip_zh="启用思维树推理框架。对复杂问题会生成多个思维分支并评估选择最优路径。",
        tooltip_en="Enable Tree of Thoughts reasoning framework. Generates multiple thought branches for complex problems and selects the best path.",
    ),
    SettingDefinition(
        key="tot_max_depth",
        type="int",
        default=2,
        group="thinking",
        section="tot",
        description_zh="最大深度",
        description_en="Max Depth",
        tooltip_zh="思维树的最大探索深度。较大的值能处理更复杂的问题但消耗更多 token。",
        tooltip_en="Maximum exploration depth for thought tree. Larger values handle more complex problems but cost more tokens.",
        range_min=1,
        range_max=5,
    ),
    SettingDefinition(
        key="tot_branching_factor",
        type="int",
        default=3,
        group="thinking",
        section="tot",
        description_zh="分支因子",
        description_en="Branching Factor",
        tooltip_zh="每个节点的子思维分支数。较多的分支提供更多选择但成倍增加计算量。",
        tooltip_en="Number of child thought branches per node. More branches provide more options but exponentially increase computation.",
        range_min=2,
        range_max=6,
    ),
    SettingDefinition(
        key="tot_quality_threshold",
        type="float",
        default=6.0,
        group="thinking",
        section="tot",
        description_zh="质量阈值",
        description_en="Quality Threshold",
        tooltip_zh="思维分支的质量评估阈值（0-10）。低于此分数的分支会被剪枝。",
        tooltip_en="Quality evaluation threshold (0-10) for thought branches. Branches below this score are pruned.",
        range_min=0,
        range_max=10,
    ),

    # ===== Group: Thinking — Deep Research =====
    SettingDefinition(
        key="enable_deep_research",
        type="bool",
        default=True,
        group="thinking",
        section="research",
        description_zh="深度研究",
        description_en="Deep Research",
        tooltip_zh="启用深度研究模式，对复杂问题进行多步骤深入分析。",
        tooltip_en="Enable deep research mode for multi-step in-depth analysis of complex problems.",
    ),
    SettingDefinition(
        key="research_mode",
        type="select",
        default="heuristic",
        group="thinking",
        section="research",
        description_zh="研究模式",
        description_en="Research Mode",
        tooltip_zh="深度研究的策略模式。启发式（快速）、分析式（深入）、穷举式（全面）。",
        tooltip_en="Deep research strategy. Heuristic (fast), Analytical (deep), Exhaustive (comprehensive).",
        options=[
            {"value": "heuristic", "label_zh": "启发式", "label_en": "Heuristic"},
            {"value": "analytical", "label_zh": "分析式", "label_en": "Analytical"},
            {"value": "exhaustive", "label_zh": "穷举式", "label_en": "Exhaustive"},
        ],
    ),

    # ===== Group: Thinking — PERV =====
    SettingDefinition(
        key="perv_router_enabled",
        type="bool",
        default=True,
        group="thinking",
        section="perv",
        description_zh="PERV 路由",
        description_en="PERV Router",
        tooltip_zh="启用 PERV（规划-执行-验证-反思）增强路由。",
        tooltip_en="Enable PERV (Plan-Execute-Verify-Reflect) enhanced routing.",
    ),
    SettingDefinition(
        key="perv_enable_post_learning",
        type="bool",
        default=True,
        group="thinking",
        section="perv",
        description_zh="后验学习",
        description_en="Post Learning",
        tooltip_zh="从执行结果中学习经验用于后续任务。",
        tooltip_en="Learn from execution results for future tasks.",
    ),
    SettingDefinition(
        key="perv_enable_pattern_retrieval",
        type="bool",
        default=True,
        group="thinking",
        section="perv",
        description_zh="模式检索",
        description_en="Pattern Retrieval",
        tooltip_zh="检索历史成功模式辅助当前任务规划。",
        tooltip_en="Retrieve historical successful patterns to aid current task planning.",
    ),
    SettingDefinition(
        key="perv_enable_strategy_injection",
        type="bool",
        default=True,
        group="thinking",
        section="perv",
        description_zh="策略注入",
        description_en="Strategy Injection",
        tooltip_zh="将学到的策略注入到任务规划中。",
        tooltip_en="Inject learned strategies into task planning.",
    ),
    SettingDefinition(
        key="perv_enable_semantic_history",
        type="bool",
        default=True,
        group="thinking",
        section="perv",
        description_zh="语义历史",
        description_en="Semantic History",
        tooltip_zh="使用语义搜索检索相关的历史执行经验。",
        tooltip_en="Use semantic search to retrieve relevant historical execution experience.",
    ),
    SettingDefinition(
        key="perv_enable_skill_policy",
        type="bool",
        default=True,
        group="thinking",
        section="perv",
        description_zh="技能策略",
        description_en="Skill Policy",
        tooltip_zh="根据任务特征动态选择和编译最佳技能组合。",
        tooltip_en="Dynamically select and compile optimal skill combinations based on task characteristics.",
    ),
    SettingDefinition(
        key="enable_rl_training",
        type="bool",
        default=True,
        group="thinking",
        section="meta_policy",
        description_zh="RL 训练",
        description_en="RL Training",
        tooltip_zh="启用强化学习训练，持续优化策略选择模型。",
        tooltip_en="Enable reinforcement learning training to continuously optimize strategy selection.",
    ),

    # ===== Group: Skills — Dependency Management =====
    SettingDefinition(
        key="enable_skill_dependency_check",
        type="bool",
        default=True,
        group="skills",
        section="dependency",
        description_zh="依赖检查",
        description_en="Dependency Check",
        tooltip_zh="启用技能依赖检查，加载技能时验证所需依赖是否已安装。",
        tooltip_en="Enable skill dependency checking — verify required dependencies are installed when loading skills.",
    ),
    SettingDefinition(
        key="auto_install_python_dependencies",
        type="bool",
        default=True,
        group="skills",
        section="dependency",
        description_zh="自动安装",
        description_en="Auto Install",
        tooltip_zh="自动安装缺失的 Python 依赖包。",
        tooltip_en="Automatically install missing Python dependency packages.",
    ),
    SettingDefinition(
        key="skill_dependency_install_timeout",
        type="int",
        default=300,
        group="skills",
        section="dependency",
        description_zh="安装超时 (秒)",
        description_en="Install Timeout (s)",
        tooltip_zh="单个依赖包安装的最大等待时间（秒）。",
        tooltip_en="Maximum wait time in seconds for installing a single dependency package.",
        range_min=30,
        range_max=600,
    ),

    # ===== Group: Performance — Streaming =====
    SettingDefinition(
        key="enable_streaming_response",
        type="bool",
        default=True,
        group="performance",
        section="streaming",
        description_zh="流式响应",
        description_en="Streaming Response",
        tooltip_zh="启用 SSE 流式输出，实时显示 Agent 思考过程。关闭后等待完整响应一次性返回。",
        tooltip_en="Enable SSE streaming output for real-time Agent thought display. Disabling waits for complete response.",
    ),
    SettingDefinition(
        key="streaming_chunk_size",
        type="int",
        default=512,
        group="performance",
        section="streaming",
        description_zh="流式块大小",
        description_en="Chunk Size",
        tooltip_zh="流式输出每次发送的字符数。较小的值延迟更低但更频繁。",
        tooltip_en="Characters per streaming chunk. Smaller values have lower latency but higher frequency.",
        range_min=128,
        range_max=4096,
    ),

    # ===== Group: Performance — Parallel =====
    SettingDefinition(
        key="enable_parallel_tool_execution",
        type="bool",
        default=True,
        group="performance",
        section="parallel",
        description_zh="并行工具执行",
        description_en="Parallel Tool Execution",
        tooltip_zh="允许多个无依赖的工具调用并行执行，加速任务处理。",
        tooltip_en="Allow independent tool calls to execute in parallel for faster processing.",
    ),
    SettingDefinition(
        key="max_concurrent_tools",
        type="int",
        default=5,
        group="performance",
        section="parallel",
        description_zh="最大并发数",
        description_en="Max Concurrent",
        tooltip_zh="同时执行的工具调用最大数量。",
        tooltip_en="Maximum number of tool calls executing simultaneously.",
        range_min=1,
        range_max=10,
    ),
    SettingDefinition(
        key="enable_auto_fallback",
        type="bool",
        default=True,
        group="performance",
        section="parallel",
        description_zh="自动回退",
        description_en="Auto Fallback",
        tooltip_zh="并行执行失败时自动回退到串行模式。",
        tooltip_en="Automatically fall back to sequential mode when parallel execution fails.",
    ),
    SettingDefinition(
        key="parallel_tool_dependency_detection",
        type="bool",
        default=True,
        group="performance",
        section="parallel",
        description_zh="依赖检测",
        description_en="Dependency Detection",
        tooltip_zh="自动检测工具调用之间的依赖关系，确保执行顺序正确。",
        tooltip_en="Auto-detect dependencies between tool calls to ensure correct execution order.",
    ),

    # ===== Group: Performance — Compression =====
    SettingDefinition(
        key="enable_smart_truncation",
        type="bool",
        default=True,
        group="performance",
        section="compression",
        description_zh="智能截断",
        description_en="Smart Truncation",
        tooltip_zh="当 Prompt 超出 token 预算时智能截断低优先级内容。",
        tooltip_en="Intelligently truncate low-priority content when Prompt exceeds token budget.",
    ),
    SettingDefinition(
        key="max_prompt_tokens",
        type="int",
        default=15000,
        group="performance",
        section="compression",
        description_zh="最大 Prompt Token",
        description_en="Max Prompt Tokens",
        tooltip_zh="发送给 LLM 的最大 token 数。超出时触发智能截断。",
        tooltip_en="Maximum tokens sent to LLM. Triggers smart truncation when exceeded.",
        range_min=1000,
        range_max=50000,
    ),

    # ===== Group: Performance — Embedding =====
    SettingDefinition(
        key="embedding_warmup_enabled",
        type="bool",
        default=True,
        group="performance",
        section="embedding",
        description_zh="Embedding 预热",
        description_en="Embedding Warmup",
        tooltip_zh="启动时预热 Embedding 模型，避免首次调用延迟过高。",
        tooltip_en="Warm up the Embedding model at startup to avoid high first-call latency.",
    ),

    # ===== Group: Logging =====
    SettingDefinition(
        key="log_level",
        type="select",
        default="INFO",
        group="logging",
        section="general",
        description_zh="日志级别",
        description_en="Log Level",
        tooltip_zh="日志输出的最低级别。DEBUG 最详细，ERROR 仅输出错误。",
        tooltip_en="Minimum log level. DEBUG is most verbose, ERROR only shows errors.",
        options=[
            {"value": "DEBUG", "label_zh": "DEBUG（调试）", "label_en": "DEBUG"},
            {"value": "INFO", "label_zh": "INFO（信息）", "label_en": "INFO"},
            {"value": "WARNING", "label_zh": "WARNING（警告）", "label_en": "WARNING"},
            {"value": "ERROR", "label_zh": "ERROR（错误）", "label_en": "ERROR"},
        ],
    ),
    SettingDefinition(
        key="log_to_file",
        type="bool",
        default=True,
        group="logging",
        section="general",
        description_zh="文件日志",
        description_en="Log to File",
        tooltip_zh="将日志写入文件（logs/ 目录）。关闭后仅输出到控制台。",
        tooltip_en="Write logs to files (logs/ directory). Disabling means console output only.",
    ),
    SettingDefinition(
        key="log_to_console",
        type="bool",
        default=True,
        group="logging",
        section="general",
        description_zh="控制台日志",
        description_en="Log to Console",
        tooltip_zh="在控制台输出日志。",
        tooltip_en="Output logs to console.",
    ),
    SettingDefinition(
        key="debug_agent",
        type="bool",
        default=True,
        group="logging",
        section="general",
        description_zh="Agent 调试",
        description_en="Agent Debug",
        tooltip_zh="启用 Agent 详细调试日志，包括工具调用细节和内部状态。",
        tooltip_en="Enable verbose Agent debug logging including tool call details and internal state.",
    ),
    SettingDefinition(
        key="log_max_bytes",
        type="int",
        default=10485760,
        group="logging",
        section="general",
        description_zh="日志大小上限",
        description_en="Max Log Size",
        tooltip_zh="单个日志文件的最大字节数（默认 10MB）。超出后自动轮转。",
        tooltip_en="Maximum bytes per log file (default 10MB). Auto-rotates when exceeded.",
        range_min=1048576,
        range_max=104857600,
    ),
    SettingDefinition(
        key="log_backup_count",
        type="int",
        default=5,
        group="logging",
        section="general",
        description_zh="备份数量",
        description_en="Backup Count",
        tooltip_zh="保留的历史日志文件数量。",
        tooltip_en="Number of historical log files to keep.",
        range_min=1,
        range_max=20,
    ),

    # ===== Group: Logging — LangSmith =====
    SettingDefinition(
        key="langchain_tracing_v2",
        type="bool",
        default=False,
        group="logging",
        section="langsmith",
        description_zh="LangSmith 追踪",
        description_en="LangSmith Tracing",
        tooltip_zh="启用 LangChain v2 追踪，将运行数据发送到 LangSmith 平台。",
        tooltip_en="Enable LangChain v2 tracing to send runtime data to LangSmith platform.",
    ),
    SettingDefinition(
        key="langchain_project",
        type="str",
        default="mini-openclaw",
        group="logging",
        section="langsmith",
        description_zh="LangSmith 项目",
        description_en="LangSmith Project",
        tooltip_zh="LangSmith 中的项目名称，用于组织和筛选追踪数据。",
        tooltip_en="Project name in LangSmith for organizing and filtering trace data.",
    ),

    # ===== Group: Tools & Security — Python REPL =====
    SettingDefinition(
        key="python_execution_mode",
        type="select",
        default="standard",
        group="tools_security",
        section="python_repl",
        description_zh="执行模式",
        description_en="Execution Mode",
        tooltip_zh="Python 代码执行的安全级别。safe（受限）、standard（标准）、free（自由）。",
        tooltip_en="Python code execution security level. safe (restricted), standard, free (unrestricted).",
        options=[
            {"value": "safe", "label_zh": "安全模式", "label_en": "Safe"},
            {"value": "standard", "label_zh": "标准模式", "label_en": "Standard"},
            {"value": "free", "label_zh": "自由模式", "label_en": "Free"},
        ],
    ),
    SettingDefinition(
        key="python_standard_timeout",
        type="int",
        default=300,
        group="tools_security",
        section="python_repl",
        description_zh="标准超时",
        description_en="Standard Timeout",
        tooltip_zh="标准模式下的代码执行超时（秒）。",
        tooltip_en="Code execution timeout in seconds for standard mode.",
        range_min=30,
        range_max=600,
    ),
    SettingDefinition(
        key="python_free_timeout",
        type="int",
        default=1800,
        group="tools_security",
        section="python_repl",
        description_zh="自由超时",
        description_en="Free Timeout",
        tooltip_zh="自由模式下的代码执行超时（秒）。",
        tooltip_en="Code execution timeout in seconds for free mode.",
        range_min=300,
        range_max=7200,
    ),
    SettingDefinition(
        key="python_safe_timeout",
        type="int",
        default=60,
        group="tools_security",
        section="python_repl",
        description_zh="安全超时",
        description_en="Safe Timeout",
        tooltip_zh="安全模式下代码执行超时（秒）。",
        tooltip_en="Code execution timeout in seconds for safe mode.",
        range_min=10,
        range_max=300,
    ),
    SettingDefinition(
        key="python_safe_memory_ratio",
        type="float",
        default=0.2,
        group="tools_security",
        section="python_repl",
        description_zh="安全内存比例",
        description_en="Safe Memory Ratio",
        tooltip_zh="安全模式允许使用的系统内存比例（0.0~1.0）。",
        tooltip_en="System memory ratio allowed in safe mode (0.0~1.0).",
        range_min=0.05,
        range_max=0.5,
    ),
    SettingDefinition(
        key="python_standard_memory_ratio",
        type="float",
        default=0.5,
        group="tools_security",
        section="python_repl",
        description_zh="标准内存比例",
        description_en="Standard Memory Ratio",
        tooltip_zh="标准模式允许使用的系统内存比例（0.0~1.0）。",
        tooltip_en="System memory ratio allowed in standard mode (0.0~1.0).",
        range_min=0.1,
        range_max=0.8,
    ),
    SettingDefinition(
        key="python_safe_max_operations",
        type="int",
        default=1_000_000,
        group="tools_security",
        section="python_repl",
        description_zh="安全最大操作数",
        description_en="Safe Max Operations",
        tooltip_zh="安全模式下允许的最大 Python 操作数，防止无限循环。",
        tooltip_en="Maximum Python operations allowed in safe mode to prevent infinite loops.",
        range_min=10000,
        range_max=10000000,
    ),

    # ===== Group: Tools & Security — Monitor =====
    SettingDefinition(
        key="python_monitor_interval",
        type="int",
        default=5,
        group="tools_security",
        section="monitor",
        description_zh="监控间隔",
        description_en="Monitor Interval",
        tooltip_zh="Python 执行监控的检查间隔（秒）。",
        tooltip_en="Check interval in seconds for Python execution monitoring.",
        range_min=1,
        range_max=30,
    ),
    SettingDefinition(
        key="python_warning_threshold",
        type="float",
        default=0.7,
        group="tools_security",
        section="monitor",
        description_zh="警告阈值",
        description_en="Warning Threshold",
        tooltip_zh="资源使用达到此比例时发出警告（0.0~1.0）。",
        tooltip_en="Emit warning when resource usage reaches this ratio (0.0~1.0).",
        range_min=0.3,
        range_max=0.95,
    ),

    # ===== Group: Tools & Security — File Access =====
    SettingDefinition(
        key="terminal_root_dir",
        type="str",
        default=".",
        group="tools_security",
        section="file_access",
        description_zh="Terminal 根目录",
        description_en="Terminal Root Dir",
        tooltip_zh="Terminal 工具允许访问的根目录。限制 Agent 可操作的文件范围。",
        tooltip_en="Root directory Terminal tool is allowed to access. Limits Agent's file operation scope.",
    ),
    SettingDefinition(
        key="read_file_root_dir",
        type="str",
        default=".",
        group="tools_security",
        section="file_access",
        description_zh="读取根目录",
        description_en="Read Root Dir",
        tooltip_zh="read_file 工具允许读取的根目录。限制 Agent 可读取的文件范围。",
        tooltip_en="Root directory read_file tool is allowed to access. Limits Agent's file read scope.",
    ),

    # ===== Group: Experimental =====
    SettingDefinition(
        key="enable_dream",
        type="bool",
        default=False,
        group="experimental",
        section="dream",
        description_zh="Dream 离线蒸馏",
        description_en="Dream Offline Distillation",
        tooltip_zh="启用离线蒸馏模块，定期从历史轨迹中提取和优化知识。",
        tooltip_en="Enable offline distillation module that periodically extracts and optimizes knowledge from historical trajectories.",
    ),
    SettingDefinition(
        key="dream_max_samples",
        type="int",
        default=3,
        group="experimental",
        section="dream",
        description_zh="最大采样数",
        description_en="Max Samples",
        tooltip_zh="每次 Dream 会话采样的最大轨迹数量。",
        tooltip_en="Maximum trajectories sampled per Dream session.",
        range_min=1,
        range_max=10,
    ),
    SettingDefinition(
        key="dream_executor_mode",
        type="str",
        default="simulated",
        group="experimental",
        section="dream",
        description_zh="执行器模式",
        description_en="Executor Mode",
        tooltip_zh="Dream 执行器模式。simulated 为模拟执行，replay 为回放历史。",
        tooltip_en="Dream executor mode. 'simulated' for simulation, 'replay' for historical replay.",
    ),
    SettingDefinition(
        key="dream_schedule",
        type="str",
        default="",
        group="experimental",
        section="dream",
        description_zh="调度计划",
        description_en="Schedule",
        tooltip_zh="Dream 自动运行的 Cron 表达式，留空则仅手动触发。示例: '0 3 * * *'（每天凌晨3点）。",
        tooltip_en="Cron expression for automatic Dream runs. Empty = manual only. Example: '0 3 * * *' (daily at 3am).",
    ),
    SettingDefinition(
        key="enable_event_log",
        type="bool",
        default=False,
        group="experimental",
        section="features",
        description_zh="事件日志",
        description_en="Event Log",
        tooltip_zh="记录详细的事件日志用于分析和调试。",
        tooltip_en="Record detailed event logs for analysis and debugging.",
    ),
    SettingDefinition(
        key="enable_case_memory",
        type="bool",
        default=False,
        group="experimental",
        section="features",
        description_zh="案例记忆",
        description_en="Case Memory",
        tooltip_zh="记录成功和失败的任务案例，用于后续相似任务的参考。",
        tooltip_en="Record successful and failed task cases for reference in similar future tasks.",
    ),
    SettingDefinition(
        key="case_memory_max_cases",
        type="int",
        default=1000,
        group="experimental",
        section="features",
        description_zh="最大案例数",
        description_en="Max Cases",
        tooltip_zh="案例记忆保存的最大案例数量。",
        tooltip_en="Maximum number of cases to keep in case memory.",
        range_min=100,
        range_max=10000,
    ),
    SettingDefinition(
        key="enable_procedural_memory",
        type="bool",
        default=False,
        group="experimental",
        section="features",
        description_zh="程序性记忆",
        description_en="Procedural Memory",
        tooltip_zh="记录操作步骤和流程，形成可复用的程序性知识。",
        tooltip_en="Record operation steps and procedures as reusable procedural knowledge.",
    ),
    SettingDefinition(
        key="enable_neural_strategy",
        type="bool",
        default=True,
        group="experimental",
        section="neural",
        description_zh="神经策略",
        description_en="Neural Strategy",
        tooltip_zh="使用神经网络模型选择执行策略。",
        tooltip_en="Use neural network model for execution strategy selection.",
    ),
    SettingDefinition(
        key="neural_strategy_auto_transition",
        type="bool",
        default=True,
        group="experimental",
        section="neural",
        description_zh="自动转换",
        description_en="Auto Transition",
        tooltip_zh="自动在不同策略之间切换。",
        tooltip_en="Automatically transition between different strategies.",
    ),
]


def get_setting_definition(key: str) -> Optional[SettingDefinition]:
    """Get a single setting definition by key."""
    for s in SETTINGS_DEFINITIONS:
        if s.key == key:
            return s
    return None


def get_all_keys() -> set:
    """Get all registered setting keys."""
    return {s.key for s in SETTINGS_DEFINITIONS}


def get_settings_by_group(group_id: str) -> List[SettingDefinition]:
    """Get all settings for a group."""
    return [s for s in SETTINGS_DEFINITIONS if s.group == group_id]


SECTIONS_REGISTRY: Dict[str, Dict[str, str]] = {
    "general": {"label_zh": "通用", "label_en": "General"},
    "session_management": {"label_zh": "会话管理", "label_en": "Session Management"},
    "master_switches": {"label_zh": "主开关", "label_en": "Master Switches"},
    "extraction": {"label_zh": "记忆提取", "label_en": "Extraction"},
    "knowledge_graph": {"label_zh": "知识图谱", "label_en": "Knowledge Graph"},
    "wiki": {"label_zh": "Wiki 笔记", "label_en": "Wiki Notes"},
    "long_term": {"label_zh": "长期记忆", "label_en": "Long-term Memory"},
    "decay": {"label_zh": "记忆衰减", "label_en": "Memory Decay"},
    "markdown": {"label_zh": "Markdown 导出", "label_en": "Markdown Export"},
    "research": {"label_zh": "搜索研究", "label_en": "Research"},
    "caching": {"label_zh": "缓存", "label_en": "Caching"},
    "tot": {"label_zh": "Tree of Thoughts", "label_en": "Tree of Thoughts"},
    "perv": {"label_zh": "PERV 模式", "label_en": "PERV Mode"},
    "reflection": {"label_zh": "反思引擎", "label_en": "Reflection Engine"},
    "watchdog": {"label_zh": "看门狗", "label_en": "Watchdog"},
    "meta_policy": {"label_zh": "元策略", "label_en": "Meta Policy"},
    "streaming": {"label_zh": "流式输出", "label_en": "Streaming"},
    "parallel": {"label_zh": "并行执行", "label_en": "Parallel Execution"},
    "compression": {"label_zh": "压缩截断", "label_en": "Compression"},
    "embedding": {"label_zh": "Embedding", "label_en": "Embedding"},
    "langsmith": {"label_zh": "LangSmith", "label_en": "LangSmith"},
    "python_repl": {"label_zh": "Python REPL", "label_en": "Python REPL"},
    "monitor": {"label_zh": "执行监控", "label_en": "Monitor"},
    "file_access": {"label_zh": "文件访问", "label_en": "File Access"},
    "dependency": {"label_zh": "依赖管理", "label_en": "Dependency Management"},
    "dream": {"label_zh": "Dream 蒸馏", "label_en": "Dream Distillation"},
    "features": {"label_zh": "实验功能", "label_en": "Experimental Features"},
    "neural": {"label_zh": "神经策略", "label_en": "Neural Strategy"},
    "agent_execution": {"label_zh": "执行控制", "label_en": "Execution Control"},
}


def get_sections_for_group(group_id: str) -> List[str]:
    """Get ordered list of section IDs for a group."""
    seen = []
    for s in SETTINGS_DEFINITIONS:
        if s.group == group_id and s.section not in seen:
            seen.append(s.section)
    return seen